spring:
  datasource:
    url: jdbc:mysql://localhost:3306/master_pedido?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: wm2CZEsS7IATE6qcW4
  jpa:
    hibernate:
      ddl-auto: update
    # Configurações para criacao do banco de dados
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#        hibernate:
#          hbm2ddl:
#            delimiter: ;


